### ISSUE TITLE
FE: Create a landing page

### ISSUE THREAD

**Issue by Mleng89** [kylejb/JobMate#5]
### Things needed to be included:
- [ ] Navbar
- [ ] Information about Jobmates

**Comment by techwil** [comment]
Hey guys are you still working on that?

**Comment by kylejb** [comment]
> Hey guys are you still working on that?

Yep - this ticket represents a workflow @Mleng89 is working on.

**Comment by YetAnotherguyhere** [comment]
If you need any help.
I would he happy to help you with my ejs, bootstrap css js skills. 😀😀
